import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Header from "@/components/layout/Header";
import Nav from "@/components/layout/Nav";
import Main from "@/components/layout/Main";
import Footer from "@/components/layout/Footer";

import {ThemeProvider} from "next-themes";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="light">
          <Header/>
          <Nav/>
          <Main>{children}</Main>
          <Footer/>
        </ThemeProvider>
      </body>
    </html>
  );
}
